services:
  riichi-advanced:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    environment:
      MIX_ENV: dev
      HTTP_PORT: "4000"
      DISABLE_HTTPS: "true"
      VALKEY_URL: "redis://valkey:6379"
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - deps:/app/deps
      - build:/app/_build
      - node_modules:/app/assets/node_modules
    depends_on:
      - valkey

  valkey:
    image: valkey/valkey:8-alpine
    ports:
      - "6379:6379"

volumes:
  deps:
  build:
  node_modules:
